#!/bin/bash

# Define the root directory to search recursively (current directory by default)


_process () {
  whisper "$@" --model "turbo" --fp16 False --output_format "vtt"
}

for i in $(find "$@" -type f | grep -E "\.mp3")
do
  _process $i
done
